version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: quarter_nestjs-server
    ports:
      - 5432:5432
    env_file:
      - .postgres.env
    volumes:
      - ./database/postgres:/var/lib/postgresql/data